version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-app
    container_name: laravel-app
    restart: unless-stopped
    ports:
      - "8002:8000"
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USERNAME=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - REDIS_HOST= ${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    depends_on:
      - db
      - redis
    volumes:
      - .:/var/www/html
    networks:
      - laravel_network

  db:
    image: mysql:8.0
    container_name: laravel-db
    restart: unless-stopped
    command: php artisan migrate
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USERNAME=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - REDIS_HOST= ${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    ports:
      - "3305:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel_network

  redis:
    image: redis:alpine
    container_name: laravel-redis
    restart: unless-stopped
    ports:
      - "6377:6379"
    networks:
      - laravel_network

  horizon:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-horizon
    restart: unless-stopped
    command: php artisan horizon
    depends_on:
      - app
      - redis
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      APP_KEY: base64:examplekey=
      REDIS_HOST: redis
      REDIS_PORT: 6379
    volumes:
      - .:/var/www/html
    networks:
      - laravel_network

networks:
  laravel_network:
    driver: bridge

volumes:
  dbdata:
